# Generated by Django 4.1.4 on 2022-12-26 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20, verbose_name="Menu title")),
                (
                    "slug",
                    models.SlugField(max_length=255, null=True, verbose_name="Slug"),
                ),
                (
                    "named_url",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Named URL"
                    ),
                ),
            ],
            options={
                "verbose_name": "menu",
                "verbose_name_plural": "menu",
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Item title")),
                (
                    "url",
                    models.CharField(blank=True, max_length=255, verbose_name="Link"),
                ),
                (
                    "named_url",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Named URL"
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="menuapp.menu",
                        verbose_name="menu",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="menuapp.menuitem",
                        verbose_name="parent menu item",
                    ),
                ),
            ],
            options={
                "verbose_name": "menu item",
                "verbose_name_plural": "menu items",
            },
        ),
    ]
